// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATl4pUCt6ZryUnZhWyo9ZMXCpdPvR9D60',
    appId: '1:74854064361:web:93105cad6b1305bba39078',
    messagingSenderId: '74854064361',
    projectId: 'calorie-tracker-d3561',
    authDomain: 'calorie-tracker-d3561.firebaseapp.com',
    storageBucket: 'calorie-tracker-d3561.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEsmvKcXX15URPhDi9RRQHY8bcwZBy6jU',
    appId: '1:74854064361:android:90c451f988029cf2a39078',
    messagingSenderId: '74854064361',
    projectId: 'calorie-tracker-d3561',
    storageBucket: 'calorie-tracker-d3561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5Ip3PUOWfldCMzp91jRx8K85PmiGLhk',
    appId: '1:74854064361:ios:2ac51545d7d1864ea39078',
    messagingSenderId: '74854064361',
    projectId: 'calorie-tracker-d3561',
    storageBucket: 'calorie-tracker-d3561.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5Ip3PUOWfldCMzp91jRx8K85PmiGLhk',
    appId: '1:74854064361:ios:2ac51545d7d1864ea39078',
    messagingSenderId: '74854064361',
    projectId: 'calorie-tracker-d3561',
    storageBucket: 'calorie-tracker-d3561.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATl4pUCt6ZryUnZhWyo9ZMXCpdPvR9D60',
    appId: '1:74854064361:web:9ecfe02b31bac0daa39078',
    messagingSenderId: '74854064361',
    projectId: 'calorie-tracker-d3561',
    authDomain: 'calorie-tracker-d3561.firebaseapp.com',
    storageBucket: 'calorie-tracker-d3561.firebasestorage.app',
  );
}
